/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 09-19-2022
 * @last modified by  : clabelle@everstream.net
**/
public class SolarwindsData {
    public String NodeID;
    public String InterfaceID;
    public DateTime CreatedDate;
    public Decimal InAveragebps;
    public Decimal InMinbps;
    public Decimal InMaxbps;
    public Decimal InTotalBytes;
    public Decimal InTotalPkts;
    public Decimal InAvgUniCastPkts;
    public Decimal InMinUniCastPkts;
    public Decimal InMaxUniCastPkts;
    public Decimal InAvgMultiCastPkts;
    public Decimal InMinMultiCastPkts;
    public Decimal InMaxMultiCastPkts;
    public Decimal OutAveragebps;
    public Decimal OutMinbps;
    public Decimal OutMaxbps;
    public Decimal OutTotalBytes;
    public Decimal OutTotalPkts;
    public Decimal OutAvgUniCastPkts;
    public Decimal OutMaxUniCastPkts;
    public Decimal OutMinUniCastPkts;
    public Decimal OutAvgMultiCastPkts;
    public Decimal OutMinMultiCastPkts;
    public Decimal OutMaxMultiCastPkts;

    public String MetricName;
    public String InstanceId;
    public Decimal PercentAvgUsage;
    public String DisplayName;
    public String Name;
    public String Description;
    public String InstanceType;
    public String Uri;
    public String InstanceSiteId;
    
    public String Status;
}